using System;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

namespace FrankRetarget.Editor
{
    public static partial class FrankRetargetBuilder
    {
        // Captures every authored direction beat, including contacts too brief to appear
        // in the six evenly spaced overview frames generated by CameraValidate.
        [MenuItem("Tools/Frank Retarget/Cameras/Capture authored action beats")]
        public static void CameraCaptureBeats()
        {
            const string folder = "/tmp/frank-camera-review/beats";
            Directory.CreateDirectory(folder);
            var plans=JsonUtility.FromJson<CameraPlans>(File.ReadAllText(Output+"/Editor/FrankCameraDirections.json")).plans;
            var scene=EditorSceneManager.OpenPreviewScene(Output+"/Frank_Damages_Mankey_Pepe.unity");
            var tester=scene.GetRootGameObjects().SelectMany(x=>x.GetComponentsInChildren<FrankCombinationTester>()).Single();
            var target=RenderTexture.GetTemporary(960,720,24,RenderTextureFormat.ARGB32);
            var manifest=new StringBuilder("key,beat,time,fov,path\n");
            try
            {
                var director=tester.cinematicCamera;
                if(!director || !director.library)throw new InvalidOperationException("Saved cinematic camera library missing");
                tester.demoCamera.scene=scene;
                foreach(var entry in CameraEntries(tester))for(int role=0;role<2;role++)
                {
                    CameraValidationSelect(tester,director,entry.family,entry.index,role);
                    var plan=plans.Single(x=>x.family==entry.family&&x.index==entry.index);
                    for(int i=0;i<plan.beats.Length;i++)
                    {
                        float time=Mathf.Min(tester.Duration,plan.beats[i]);
                        CameraValidationEvaluate(tester,director,target,time,true,0);
                        string path=folder+"/"+entry.family+"-"+entry.index+"-"+(role==0?"mankey":"pepe")+"-"+i.ToString("00")+".png";
                        tester.demoCamera.Render();Capture(tester.demoCamera,path,960,720);
                        manifest.AppendLine(CameraValidationCsv(FrankCinematicCamera.CurrentKey(tester))+","+i+","+CameraValidationNumber(time)+","+CameraValidationNumber(tester.demoCamera.fieldOfView)+","+CameraValidationCsv(path));
                    }
                }
                File.WriteAllText(folder+"/Beats.csv",manifest.ToString());
                Debug.Log("Captured every authored beat for all 94 camera takes");
            }
            finally
            {
                tester.demoCamera.targetTexture=null;
                tester.mankey.Clear();tester.pepe.Clear();RenderTexture.ReleaseTemporary(target);
                EditorSceneManager.ClosePreviewScene(scene);
            }
        }
    }
}
